@Albums.API_HostAddress = http://localhost:27017


###
GET {{Albums.API_HostAddress}}/get-all
Content-Type: application/json

{}

###
GET {{Albums.API_HostAddress}}/get-by-id/1
Content-Type: application/json

{}

###
POST {{Albums.API_HostAddress}}/add
Content-Type: application/json

{
  "NewAlbum":{
      "title": "In Utero",
      "artist": "Nirvana",
      "genre": "AlternativeAndPunk",
      "tracks": [
        {
          "artist": "Nirvana",
         "name": "Song name",
         "length": 2.43
        }
      ],
      "price": 1.99
  }
}